/**
 * Comprehensive emoji dataset grouped by category.
 * ~1500+ emojis covering all standard Unicode emoji categories.
 */

export interface EmojiItem {
  emoji: string;
  name: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: EmojiItem[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    label: "Smileys & People",
    icon: "😀",
    emojis: [
      { emoji: "😀", name: "grinning face", keywords: ["happy", "smile", "grin", "joy"] },
      { emoji: "😃", name: "grinning face with big eyes", keywords: ["happy", "smile", "joy", "haha"] },
      { emoji: "😄", name: "grinning face with smiling eyes", keywords: ["happy", "smile", "laugh", "joy"] },
      { emoji: "😁", name: "beaming face with smiling eyes", keywords: ["happy", "smile", "grin", "satisfied"] },
      { emoji: "😆", name: "grinning squinting face", keywords: ["happy", "laugh", "LOL", "satisfied", "haha"] },
      { emoji: "😅", name: "grinning face with sweat", keywords: ["hot", "happy", "laugh", "awkward", "nervous"] },
      { emoji: "🤣", name: "rolling on the floor laughing", keywords: ["rofl", "laugh", "funny", "hilarious"] },
      { emoji: "😂", name: "face with tears of joy", keywords: ["joy", "laugh", "lol", "funny", "tears", "haha"] },
      { emoji: "🙂", name: "slightly smiling face", keywords: ["smile", "happy", "pleased"] },
      { emoji: "🙃", name: "upside-down face", keywords: ["silly", "sarcasm", "irony"] },
      { emoji: "🫠", name: "melting face", keywords: ["melt", "dissolve", "awkward"] },
      { emoji: "😉", name: "winking face", keywords: ["wink", "flirt", "joke"] },
      { emoji: "😊", name: "smiling face with smiling eyes", keywords: ["blush", "happy", "warm", "pleased"] },
      { emoji: "😇", name: "smiling face with halo", keywords: ["angel", "innocent", "halo", "good"] },
      { emoji: "🥰", name: "smiling face with hearts", keywords: ["love", "adore", "hearts", "crush"] },
      { emoji: "😍", name: "smiling face with heart-eyes", keywords: ["love", "heart eyes", "adore", "crush"] },
      { emoji: "🤩", name: "star-struck", keywords: ["star", "eyes", "starstruck", "excited", "wow"] },
      { emoji: "😘", name: "face blowing a kiss", keywords: ["kiss", "love", "flirt"] },
      { emoji: "😗", name: "kissing face", keywords: ["kiss", "love"] },
      { emoji: "☺️", name: "smiling face", keywords: ["smile", "happy", "warm"] },
      { emoji: "😚", name: "kissing face with closed eyes", keywords: ["kiss", "love", "blush"] },
      { emoji: "😙", name: "kissing face with smiling eyes", keywords: ["kiss", "love", "smile"] },
      { emoji: "🥲", name: "smiling face with tear", keywords: ["sad", "proud", "grateful", "emotional"] },
      { emoji: "😋", name: "face savoring food", keywords: ["yummy", "delicious", "food", "nom"] },
      { emoji: "😛", name: "face with tongue", keywords: ["tongue", "playful", "silly"] },
      { emoji: "😜", name: "winking face with tongue", keywords: ["wink", "tongue", "silly", "playful"] },
      { emoji: "🤪", name: "zany face", keywords: ["crazy", "wild", "goofy", "silly"] },
      { emoji: "😝", name: "squinting face with tongue", keywords: ["tongue", "silly", "gross"] },
      { emoji: "🤑", name: "money-mouth face", keywords: ["money", "rich", "dollar", "greedy"] },
      { emoji: "🤗", name: "smiling face with open hands", keywords: ["hug", "hugging", "happy", "warm"] },
      { emoji: "🫡", name: "saluting face", keywords: ["salute", "respect", "soldier", "serious"] },
      { emoji: "🤔", name: "thinking face", keywords: ["thinking", "hmm", "ponder", "consider"] },
      { emoji: "🫢", name: "face with open eyes and hand over mouth", keywords: ["shocked", "surprise", "secret", "quiet"] },
      { emoji: "🫣", name: "face with peeking eye", keywords: ["peek", "shy", "scared", "curious"] },
      { emoji: "🤭", name: "face with hand over mouth", keywords: ["hehe", "quiet", "oops", "secret"] },
      { emoji: "🤫", name: "shushing face", keywords: ["shush", "quiet", "secret", "sssh"] },
      { emoji: "🤥", name: "lying face", keywords: ["lie", "pinocchio", "dishonest"] },
      { emoji: "🫨", name: "shaking face", keywords: ["shocked", "disbelief", "tremble"] },
      { emoji: "😶", name: "face without mouth", keywords: ["mute", "quiet", "speechless"] },
      { emoji: "🫥", name: "dotted line face", keywords: ["invisible", "hidden", "blank"] },
      { emoji: "😐", name: "neutral face", keywords: ["meh", "neutral", "blank", "expressionless"] },
      { emoji: "😑", name: "expressionless face", keywords: ["expressionless", "meh", "blank", "deadpan"] },
      { emoji: "😬", name: "grimacing face", keywords: ["grimace", "oops", "nervous", "awkward"] },
      { emoji: "🙄", name: "face with rolling eyes", keywords: ["eye roll", "sigh", "whatever", "bored"] },
      { emoji: "😯", name: "hushed face", keywords: ["surprised", "hushed", "silence", "awe"] },
      { emoji: "😦", name: "frowning face with open mouth", keywords: ["surprised", "shocked", "frown"] },
      { emoji: "😧", name: "anguished face", keywords: ["anguished", "distressed", "shocked"] },
      { emoji: "😮", name: "face with open mouth", keywords: ["surprised", "shock", "wow", "gasp"] },
      { emoji: "🤯", name: "exploding head", keywords: ["mind blown", "explosion", "shocked", "wow"] },
      { emoji: "😲", name: "astonished face", keywords: ["astonished", "shocked", "surprised", "wow"] },
      { emoji: "🥹", name: "face holding back tears", keywords: ["moved", "touched", "emotional", "holding back"] },
      { emoji: "😴", name: "sleeping face", keywords: ["sleep", "tired", "zzz", "bored"] },
      { emoji: "🤤", name: "drooling face", keywords: ["drool", "hungry", "food", "want"] },
      { emoji: "😪", name: "sleepy face", keywords: ["sleepy", "tired", "bored", "snot"] },
      { emoji: "😵", name: "face with crossed-out eyes", keywords: ["dizzy", "dead", "knocked out", "spiral"] },
      { emoji: "😵‍💫", name: "face with spiral eyes", keywords: ["dizzy", "hypnotized", "spiral", "confused"] },
      { emoji: "🤐", name: "zipper-mouth face", keywords: ["zip", "quiet", "secret", "silence"] },
      { emoji: "🥴", name: "woozy face", keywords: ["drunk", "dizzy", "woozy", "sick"] },
      { emoji: "🤢", name: "nauseated face", keywords: ["sick", "nausea", "green", "vomit", "gross"] },
      { emoji: "🤮", name: "face vomiting", keywords: ["sick", "vomit", "gross", "ill"] },
      { emoji: "🤧", name: "sneezing face", keywords: ["sick", "sneeze", "cold", "tissue", "allergy"] },
      { emoji: "🥵", name: "hot face", keywords: ["hot", "sweating", "flushed", "heat"] },
      { emoji: "🥶", name: "cold face", keywords: ["cold", "freezing", "blue", "ice", "chilly"] },
      { emoji: "🥺", name: "pleading face", keywords: ["puppy eyes", "begging", "please", "sad", "cute"] },
      { emoji: "😱", name: "face screaming in fear", keywords: ["scream", "horror", "fear", "shocked"] },
      { emoji: "😨", name: "fearful face", keywords: ["scared", "fear", "shocked", "surprised"] },
      { emoji: "😰", name: "anxious face with sweat", keywords: ["anxious", "nervous", "sweat", "cold"] },
      { emoji: "😥", name: "sad but relieved face", keywords: ["sad", "relieved", "disappointed", "worried"] },
      { emoji: "😢", name: "crying face", keywords: ["cry", "sad", "tears", "unhappy"] },
      { emoji: "😭", name: "loudly crying face", keywords: ["cry", "sad", "sob", "tears", "heartbroken"] },
      { emoji: "😤", name: "face with steam from nose", keywords: ["triumph", "huff", "angry", "frustrated"] },
      { emoji: "😠", name: "angry face", keywords: ["angry", "mad", "furious", "grumpy"] },
      { emoji: "😡", name: "enraged face", keywords: ["rage", "angry", "mad", "furious"] },
      { emoji: "🤬", name: "face with symbols on mouth", keywords: ["cursing", "swearing", "angry", "rage"] },
      { emoji: "😈", name: "smiling face with horns", keywords: ["devil", "evil", "mischief", "naughty"] },
      { emoji: "👿", name: "angry face with horns", keywords: ["devil", "evil", "angry", "imp"] },
      { emoji: "💀", name: "skull", keywords: ["dead", "skeleton", "death", "danger"] },
      { emoji: "☠️", name: "skull and crossbones", keywords: ["dead", "danger", "poison", "pirates"] },
      { emoji: "💩", name: "pile of poo", keywords: ["poop", "funny", "joke", "stinky"] },
      { emoji: "🤡", name: "clown face", keywords: ["clown", "funny", "circus", "creepy"] },
      { emoji: "👹", name: "ogre", keywords: ["ogre", "monster", "halloween", "scary"] },
      { emoji: "👺", name: "goblin", keywords: ["goblin", "evil", "monster", "scary"] },
      { emoji: "👻", name: "ghost", keywords: ["ghost", "boo", "halloween", "spirit", "scary"] },
      { emoji: "👽", name: "alien", keywords: ["alien", "ufo", "space", "extraterrestrial"] },
      { emoji: "👾", name: "alien monster", keywords: ["alien", "game", "pixel", "retro", "space"] },
      { emoji: "🤖", name: "robot", keywords: ["robot", "bot", "ai", "machine", "tech"] },
      { emoji: "😺", name: "grinning cat", keywords: ["cat", "smile", "happy", "grin"] },
      { emoji: "😸", name: "grinning cat with smiling eyes", keywords: ["cat", "happy", "smile", "haha"] },
      { emoji: "😹", name: "cat with tears of joy", keywords: ["cat", "joy", "laugh", "tears"] },
      { emoji: "😻", name: "smiling cat with heart-eyes", keywords: ["cat", "love", "heart", "adore"] },
      { emoji: "😼", name: "cat with wry smile", keywords: ["cat", "sarcasm", "smirk"] },
      { emoji: "😽", name: "kissing cat", keywords: ["cat", "kiss", "love"] },
      { emoji: "🙀", name: "weary cat", keywords: ["cat", "shocked", "surprised", "weary"] },
      { emoji: "😿", name: "crying cat", keywords: ["cat", "cry", "sad", "tears"] },
      { emoji: "😾", name: "pouting cat", keywords: ["cat", "angry", "pouting", "grumpy"] },
    ],
  },
  {
    id: "people",
    label: "People & Body",
    icon: "👋",
    emojis: [
      { emoji: "👋", name: "waving hand", keywords: ["wave", "hello", "bye", "hi", "greeting"] },
      { emoji: "🤚", name: "raised back of hand", keywords: ["hand", "stop", "raised"] },
      { emoji: "🖐️", name: "hand with fingers splayed", keywords: ["hand", "five", "stop"] },
      { emoji: "✋", name: "raised hand", keywords: ["hand", "stop", "high five", "raised"] },
      { emoji: "🖖", name: "vulcan salute", keywords: ["spock", "vulcan", "star trek", "hand"] },
      { emoji: "🫱", name: "rightwards hand", keywords: ["hand", "right", "offer"] },
      { emoji: "🫲", name: "leftwards hand", keywords: ["hand", "left", "offer"] },
      { emoji: "🫳", name: "palm down hand", keywords: ["hand", "down", "dismiss"] },
      { emoji: "🫴", name: "palm up hand", keywords: ["hand", "up", "offer", "ask"] },
      { emoji: "👌", name: "ok hand", keywords: ["ok", "okay", "perfect", "agree", "hand"] },
      { emoji: "🤌", name: "pinched fingers", keywords: ["italian", "chef's kiss", "pinch", "gesture"] },
      { emoji: "🤏", name: "pinching hand", keywords: ["small", "tiny", "pinch", "little"] },
      { emoji: "✌️", name: "victory hand", keywords: ["peace", "victory", "two", "v"] },
      { emoji: "🤞", name: "crossed fingers", keywords: ["luck", "hope", "wish", "cross"] },
      { emoji: "🫰", name: "hand with index finger and thumb crossed", keywords: ["snap", "money", "love", "small"] },
      { emoji: "🤟", name: "love-you gesture", keywords: ["love", "rock on", "hand", "ILY"] },
      { emoji: "🤘", name: "sign of the horns", keywords: ["rock", "horns", "metal", "cool"] },
      { emoji: "🤙", name: "call me hand", keywords: ["call me", "shaka", "hang loose", "phone"] },
      { emoji: "👈", name: "backhand index pointing left", keywords: ["point", "left", "direction"] },
      { emoji: "👉", name: "backhand index pointing right", keywords: ["point", "right", "direction"] },
      { emoji: "👆", name: "backhand index pointing up", keywords: ["point", "up", "direction"] },
      { emoji: "🖕", name: "middle finger", keywords: ["middle finger", "rude", "offensive"] },
      { emoji: "👇", name: "backhand index pointing down", keywords: ["point", "down", "direction"] },
      { emoji: "☝️", name: "index pointing up", keywords: ["point", "up", "one", "first"] },
      { emoji: "🫵", name: "index pointing at the viewer", keywords: ["you", "point", "accuse", "choose"] },
      { emoji: "👍", name: "thumbs up", keywords: ["like", "good", "yes", "ok", "approve", "thumbs up"] },
      { emoji: "👎", name: "thumbs down", keywords: ["dislike", "bad", "no", "disapprove", "thumbs down"] },
      { emoji: "✊", name: "raised fist", keywords: ["fist", "power", "solidarity", "punch"] },
      { emoji: "👊", name: "oncoming fist", keywords: ["punch", "fist", "hit"] },
      { emoji: "🤛", name: "left-facing fist", keywords: ["fist bump", "left", "power"] },
      { emoji: "🤜", name: "right-facing fist", keywords: ["fist bump", "right", "power"] },
      { emoji: "👏", name: "clapping hands", keywords: ["clap", "applause", "bravo", "congrats"] },
      { emoji: "🙌", name: "raising hands", keywords: ["celebrate", "praise", "hooray", "hands up"] },
      { emoji: "🫶", name: "heart hands", keywords: ["love", "heart", "care", "kindness"] },
      { emoji: "👐", name: "open hands", keywords: ["open", "hug", "offering", "jazz hands"] },
      { emoji: "🤲", name: "palms up together", keywords: ["pray", "offering", "please", "ask"] },
      { emoji: "🤝", name: "handshake", keywords: ["deal", "agreement", "shake", "partnership"] },
      { emoji: "🙏", name: "folded hands", keywords: ["pray", "please", "hope", "namaste", "thank you"] },
      { emoji: "✍️", name: "writing hand", keywords: ["write", "pen", "author", "editing"] },
      { emoji: "💅", name: "nail polish", keywords: ["nails", "polish", "manicure", "beauty", "extra"] },
      { emoji: "🤳", name: "selfie", keywords: ["selfie", "phone", "camera", "photo"] },
      { emoji: "💪", name: "flexed biceps", keywords: ["muscle", "strong", "flex", "arm", "power"] },
      { emoji: "🦾", name: "mechanical arm", keywords: ["robot", "arm", "prosthetic", "bionic"] },
      { emoji: "🦿", name: "mechanical leg", keywords: ["robot", "leg", "prosthetic", "bionic"] },
      { emoji: "🦵", name: "leg", keywords: ["leg", "kick", "limb"] },
      { emoji: "🦶", name: "foot", keywords: ["foot", "stomp", "kick"] },
      { emoji: "👂", name: "ear", keywords: ["ear", "hear", "listen", "audio"] },
      { emoji: "🦻", name: "ear with hearing aid", keywords: ["ear", "deaf", "hearing", "aid"] },
      { emoji: "👃", name: "nose", keywords: ["nose", "smell", "sniff"] },
      { emoji: "🧠", name: "brain", keywords: ["brain", "smart", "think", "mind", "intelligence"] },
      { emoji: "🫀", name: "anatomical heart", keywords: ["heart", "organ", "love", "medical"] },
      { emoji: "🫁", name: "lungs", keywords: ["lungs", "breathe", "organ", "medical"] },
      { emoji: "🦷", name: "tooth", keywords: ["tooth", "dentist", "teeth"] },
      { emoji: "🦴", name: "bone", keywords: ["bone", "skeleton", "dog"] },
      { emoji: "👀", name: "eyes", keywords: ["eyes", "look", "see", "watch", "creep"] },
      { emoji: "👁️", name: "eye", keywords: ["eye", "look", "see", "view"] },
      { emoji: "👅", name: "tongue", keywords: ["tongue", "taste", "lick", "mouth"] },
      { emoji: "👄", name: "mouth", keywords: ["lips", "mouth", "kiss", "speak"] },
      { emoji: "🫦", name: "biting lip", keywords: ["lip", "bite", "nervous", "flirt", "seductive"] },
      { emoji: "👶", name: "baby", keywords: ["baby", "infant", "child", "newborn"] },
      { emoji: "🧒", name: "child", keywords: ["child", "kid", "young"] },
      { emoji: "👦", name: "boy", keywords: ["boy", "male", "child", "kid"] },
      { emoji: "👧", name: "girl", keywords: ["girl", "female", "child", "kid"] },
      { emoji: "🧑", name: "person", keywords: ["person", "adult", "human"] },
      { emoji: "👱", name: "person blond hair", keywords: ["blonde", "blond", "hair", "person"] },
      { emoji: "👨", name: "man", keywords: ["man", "male", "adult", "guy"] },
      { emoji: "🧔", name: "person beard", keywords: ["beard", "man", "facial hair"] },
      { emoji: "👩", name: "woman", keywords: ["woman", "female", "adult", "girl"] },
      { emoji: "🧓", name: "older person", keywords: ["old", "elderly", "senior"] },
      { emoji: "👴", name: "old man", keywords: ["old", "elderly", "senior", "grandfather"] },
      { emoji: "👵", name: "old woman", keywords: ["old", "elderly", "senior", "grandmother"] },
      { emoji: "🙍", name: "person frowning", keywords: ["frown", "disapprove", "sad"] },
      { emoji: "🙎", name: "person pouting", keywords: ["pout", "sulk", "mood"] },
      { emoji: "🙅", name: "person gesturing no", keywords: ["no", "stop", "refuse", "x"] },
      { emoji: "🙆", name: "person gesturing ok", keywords: ["ok", "agree", "yes", "okay"] },
      { emoji: "💁", name: "person tipping hand", keywords: ["info", "help", "sassy", "hand"] },
      { emoji: "🙋", name: "person raising hand", keywords: ["raise hand", "question", "volunteer"] },
      { emoji: "🧏", name: "deaf person", keywords: ["deaf", "listen", "sign language"] },
      { emoji: "🙇", name: "person bowing", keywords: ["bow", "sorry", "apology", "respect"] },
      { emoji: "🤦", name: "person facepalming", keywords: ["facepalm", "stupid", "embarrassed", "doh"] },
      { emoji: "🤷", name: "person shrugging", keywords: ["shrug", "whatever", "idk", "dunno", "confused"] },
      { emoji: "💆", name: "person getting massage", keywords: ["massage", "relax", "spa"] },
      { emoji: "💇", name: "person getting haircut", keywords: ["haircut", "barber", "salon"] },
      { emoji: "🚶", name: "person walking", keywords: ["walk", "stroll", "pedestrian"] },
      { emoji: "🧍", name: "person standing", keywords: ["stand", "person", "upright"] },
      { emoji: "🧎", name: "person kneeling", keywords: ["kneel", "pray", "propose"] },
      { emoji: "🏃", name: "person running", keywords: ["run", "jog", "sprint", "exercise", "fast"] },
      { emoji: "💃", name: "woman dancing", keywords: ["dance", "salsa", "celebration", "dancing"] },
      { emoji: "🕺", name: "man dancing", keywords: ["dance", "disco", "celebration", "dancing"] },
      { emoji: "🕴️", name: "person in suit levitating", keywords: ["levitate", "suit", "hover", "business"] },
      { emoji: "👫", name: "woman and man holding hands", keywords: ["couple", "date", "relationship", "love"] },
      { emoji: "👬", name: "men holding hands", keywords: ["couple", "brothers", "relationship", "gay"] },
      { emoji: "👭", name: "women holding hands", keywords: ["couple", "sisters", "relationship", "lesbian"] },
      { emoji: "💑", name: "couple with heart", keywords: ["love", "couple", "romance", "heart"] },
      { emoji: "💏", name: "kiss", keywords: ["kiss", "couple", "romance", "love"] },
      { emoji: "👪", name: "family", keywords: ["family", "home", "parents", "children"] },
      { emoji: "🫂", name: "people hugging", keywords: ["hug", "embrace", "comfort", "love"] },
    ],
  },
  {
    id: "animals",
    label: "Animals & Nature",
    icon: "🐶",
    emojis: [
      { emoji: "🐶", name: "dog face", keywords: ["dog", "puppy", "pet", "animal", "canine"] },
      { emoji: "🐱", name: "cat face", keywords: ["cat", "kitty", "pet", "animal", "kitten"] },
      { emoji: "🐭", name: "mouse face", keywords: ["mouse", "animal", "small"] },
      { emoji: "🐹", name: "hamster", keywords: ["hamster", "pet", "animal", "small"] },
      { emoji: "🐰", name: "rabbit face", keywords: ["rabbit", "bunny", "easter", "animal"] },
      { emoji: "🦊", name: "fox", keywords: ["fox", "animal", "clever", "sly"] },
      { emoji: "🐻", name: "bear", keywords: ["bear", "animal", "teddy"] },
      { emoji: "🐼", name: "panda", keywords: ["panda", "bear", "china", "animal"] },
      { emoji: "🐻‍❄️", name: "polar bear", keywords: ["polar bear", "ice", "arctic", "white"] },
      { emoji: "🐨", name: "koala", keywords: ["koala", "australia", "animal"] },
      { emoji: "🐯", name: "tiger face", keywords: ["tiger", "cat", "animal", "fierce"] },
      { emoji: "🦁", name: "lion", keywords: ["lion", "king", "animal", "fierce"] },
      { emoji: "🐮", name: "cow face", keywords: ["cow", "moo", "animal", "farm"] },
      { emoji: "🐷", name: "pig face", keywords: ["pig", "oink", "animal", "farm"] },
      { emoji: "🐸", name: "frog", keywords: ["frog", "animal", "green", "pond"] },
      { emoji: "🐵", name: "monkey face", keywords: ["monkey", "animal", "primate"] },
      { emoji: "🙈", name: "see-no-evil monkey", keywords: ["monkey", "see no evil", "hide", "shy"] },
      { emoji: "🙉", name: "hear-no-evil monkey", keywords: ["monkey", "hear no evil", "ears"] },
      { emoji: "🙊", name: "speak-no-evil monkey", keywords: ["monkey", "speak no evil", "quiet", "shush"] },
      { emoji: "🐒", name: "monkey", keywords: ["monkey", "animal", "primate", "ape"] },
      { emoji: "🦆", name: "duck", keywords: ["duck", "bird", "quack", "animal"] },
      { emoji: "🐦", name: "bird", keywords: ["bird", "tweet", "animal", "fly"] },
      { emoji: "🦅", name: "eagle", keywords: ["eagle", "bird", "freedom", "majestic"] },
      { emoji: "🦉", name: "owl", keywords: ["owl", "bird", "night", "wise"] },
      { emoji: "🦇", name: "bat", keywords: ["bat", "night", "vampire", "animal", "halloween"] },
      { emoji: "🐺", name: "wolf", keywords: ["wolf", "animal", "howl", "wild"] },
      { emoji: "🐗", name: "boar", keywords: ["boar", "pig", "wild", "animal"] },
      { emoji: "🐴", name: "horse face", keywords: ["horse", "animal", "farm", "neigh"] },
      { emoji: "🦄", name: "unicorn", keywords: ["unicorn", "magic", "rainbow", "fantasy", "mythical"] },
      { emoji: "🐝", name: "honeybee", keywords: ["bee", "honey", "insect", "sting"] },
      { emoji: "🪱", name: "worm", keywords: ["worm", "earthworm", "soil", "bug"] },
      { emoji: "🐛", name: "bug", keywords: ["bug", "insect", "caterpillar", "larva"] },
      { emoji: "🦋", name: "butterfly", keywords: ["butterfly", "insect", "transformation", "beauty"] },
      { emoji: "🐌", name: "snail", keywords: ["snail", "slow", "shell", "animal"] },
      { emoji: "🐞", name: "ladybug", keywords: ["ladybug", "ladybird", "bug", "insect", "lucky"] },
      { emoji: "🐜", name: "ant", keywords: ["ant", "insect", "bug", "colony"] },
      { emoji: "🪲", name: "beetle", keywords: ["beetle", "bug", "insect"] },
      { emoji: "🦟", name: "mosquito", keywords: ["mosquito", "bug", "bite", "insect"] },
      { emoji: "🦗", name: "cricket", keywords: ["cricket", "insect", "chirp", "bug"] },
      { emoji: "🪳", name: "cockroach", keywords: ["cockroach", "bug", "pest", "gross"] },
      { emoji: "🕷️", name: "spider", keywords: ["spider", "web", "arachnid", "creepy"] },
      { emoji: "🦂", name: "scorpion", keywords: ["scorpion", "zodiac", "danger", "animal"] },
      { emoji: "🐢", name: "turtle", keywords: ["turtle", "slow", "shell", "reptile", "ocean"] },
      { emoji: "🐍", name: "snake", keywords: ["snake", "reptile", "slither", "danger"] },
      { emoji: "🦎", name: "lizard", keywords: ["lizard", "reptile", "gecko", "animal"] },
      { emoji: "🦖", name: "t-rex", keywords: ["trex", "dinosaur", "extinct", "prehistoric"] },
      { emoji: "🦕", name: "sauropod", keywords: ["dinosaur", "brontosaurus", "extinct", "prehistoric"] },
      { emoji: "🐊", name: "crocodile", keywords: ["crocodile", "alligator", "reptile", "danger"] },
      { emoji: "🐸", name: "frog", keywords: ["frog", "animal", "green", "pond"] },
      { emoji: "🐲", name: "dragon face", keywords: ["dragon", "fantasy", "fire", "mythical"] },
      { emoji: "🐉", name: "dragon", keywords: ["dragon", "fantasy", "fire", "mythical"] },
      { emoji: "🦕", name: "sauropod dinosaur", keywords: ["dinosaur", "long neck", "prehistoric"] },
      { emoji: "🐳", name: "spouting whale", keywords: ["whale", "ocean", "water", "spout"] },
      { emoji: "🐋", name: "whale", keywords: ["whale", "ocean", "mammal", "large"] },
      { emoji: "🐬", name: "dolphin", keywords: ["dolphin", "ocean", "smart", "mammal"] },
      { emoji: "🦭", name: "seal", keywords: ["seal", "ocean", "mammal", "arctic"] },
      { emoji: "🐟", name: "fish", keywords: ["fish", "ocean", "sea", "animal"] },
      { emoji: "🐠", name: "tropical fish", keywords: ["fish", "tropical", "colorful", "ocean"] },
      { emoji: "🐡", name: "blowfish", keywords: ["blowfish", "puffer", "fish", "ocean"] },
      { emoji: "🦈", name: "shark", keywords: ["shark", "ocean", "danger", "fish", "jaws"] },
      { emoji: "🐙", name: "octopus", keywords: ["octopus", "ocean", "tentacles", "sea"] },
      { emoji: "🐚", name: "spiral shell", keywords: ["shell", "snail", "ocean", "spiral"] },
      { emoji: "🪸", name: "coral", keywords: ["coral", "reef", "ocean", "underwater"] },
      { emoji: "🦀", name: "crab", keywords: ["crab", "ocean", "seafood", "animal"] },
      { emoji: "🦞", name: "lobster", keywords: ["lobster", "seafood", "ocean", "red"] },
      { emoji: "🦐", name: "shrimp", keywords: ["shrimp", "seafood", "ocean", "small"] },
      { emoji: "🦑", name: "squid", keywords: ["squid", "calamari", "ocean", "tentacles"] },
      { emoji: "🦪", name: "oyster", keywords: ["oyster", "seafood", "pearl", "ocean"] },
      { emoji: "🐾", name: "paw prints", keywords: ["paw", "pet", "dog", "cat", "animal"] },
      { emoji: "🌵", name: "cactus", keywords: ["cactus", "desert", "plant", "spiky"] },
      { emoji: "🎄", name: "christmas tree", keywords: ["christmas", "tree", "holiday", "xmas"] },
      { emoji: "🌲", name: "evergreen tree", keywords: ["tree", "pine", "forest", "nature"] },
      { emoji: "🌳", name: "deciduous tree", keywords: ["tree", "nature", "forest", "oak"] },
      { emoji: "🌴", name: "palm tree", keywords: ["palm", "tropical", "beach", "holiday"] },
      { emoji: "🪵", name: "wood", keywords: ["wood", "log", "timber", "tree"] },
      { emoji: "🌱", name: "seedling", keywords: ["plant", "sprout", "grow", "seed", "small"] },
      { emoji: "🌿", name: "herb", keywords: ["herb", "plant", "leaf", "green", "nature"] },
      { emoji: "☘️", name: "shamrock", keywords: ["shamrock", "clover", "lucky", "irish", "green"] },
      { emoji: "🍀", name: "four leaf clover", keywords: ["lucky", "clover", "four leaf", "green"] },
      { emoji: "🎋", name: "tanabata tree", keywords: ["bamboo", "wish", "japanese", "tree"] },
      { emoji: "🎍", name: "pine decoration", keywords: ["pine", "japanese", "new year", "decoration"] },
      { emoji: "🍃", name: "leaf fluttering in wind", keywords: ["leaf", "wind", "nature", "flutter"] },
      { emoji: "🍂", name: "fallen leaf", keywords: ["leaf", "fall", "autumn", "nature"] },
      { emoji: "🍁", name: "maple leaf", keywords: ["maple", "canada", "fall", "autumn", "leaf"] },
      { emoji: "🪺", name: "nest with eggs", keywords: ["nest", "eggs", "bird", "nature"] },
      { emoji: "🪹", name: "empty nest", keywords: ["nest", "empty", "bird", "nature"] },
      { emoji: "🍄", name: "mushroom", keywords: ["mushroom", "fungus", "forest", "nature"] },
      { emoji: "🌾", name: "sheaf of rice", keywords: ["rice", "wheat", "grain", "harvest"] },
      { emoji: "💐", name: "bouquet", keywords: ["bouquet", "flowers", "gift", "love"] },
      { emoji: "🌷", name: "tulip", keywords: ["tulip", "flower", "spring", "pink"] },
      { emoji: "🌹", name: "rose", keywords: ["rose", "flower", "love", "romance", "red"] },
      { emoji: "🥀", name: "wilted flower", keywords: ["wilted", "dead", "sad", "flower", "rose"] },
      { emoji: "🌺", name: "hibiscus", keywords: ["hibiscus", "flower", "tropical", "pink"] },
      { emoji: "🌸", name: "cherry blossom", keywords: ["cherry blossom", "spring", "japan", "pink", "flower"] },
      { emoji: "🌼", name: "blossom", keywords: ["blossom", "flower", "spring", "yellow"] },
      { emoji: "🌻", name: "sunflower", keywords: ["sunflower", "flower", "sun", "yellow", "bright"] },
      { emoji: "🌞", name: "sun with face", keywords: ["sun", "summer", "hot", "bright", "happy"] },
      { emoji: "🌝", name: "full moon face", keywords: ["moon", "face", "night", "full moon"] },
      { emoji: "🌛", name: "first quarter moon face", keywords: ["moon", "crescent", "night"] },
      { emoji: "🌜", name: "last quarter moon face", keywords: ["moon", "crescent", "night"] },
      { emoji: "🌚", name: "new moon face", keywords: ["moon", "dark", "night", "new"] },
      { emoji: "🌕", name: "full moon", keywords: ["moon", "full", "night", "circle"] },
      { emoji: "🌖", name: "waning gibbous moon", keywords: ["moon", "waning", "night"] },
      { emoji: "🌗", name: "last quarter moon", keywords: ["moon", "quarter", "night"] },
      { emoji: "🌘", name: "waning crescent moon", keywords: ["moon", "crescent", "waning", "night"] },
      { emoji: "🌑", name: "new moon", keywords: ["moon", "new", "dark", "night"] },
      { emoji: "🌒", name: "waxing crescent moon", keywords: ["moon", "crescent", "waxing"] },
      { emoji: "🌓", name: "first quarter moon", keywords: ["moon", "quarter", "night"] },
      { emoji: "🌔", name: "waxing gibbous moon", keywords: ["moon", "waxing", "night"] },
      { emoji: "🌙", name: "crescent moon", keywords: ["moon", "night", "crescent", "sleep"] },
      { emoji: "🌟", name: "glowing star", keywords: ["star", "glow", "shine", "sparkle"] },
      { emoji: "⭐", name: "star", keywords: ["star", "favorite", "rating", "gold"] },
      { emoji: "🌠", name: "shooting star", keywords: ["shooting star", "wish", "night", "sky"] },
      { emoji: "⛅", name: "sun behind cloud", keywords: ["cloud", "sun", "partly cloudy", "weather"] },
      { emoji: "⛈️", name: "cloud with lightning and rain", keywords: ["storm", "thunder", "rain", "lightning"] },
      { emoji: "🌤️", name: "sun behind small cloud", keywords: ["sun", "cloud", "weather", "partly sunny"] },
      { emoji: "🌥️", name: "sun behind large cloud", keywords: ["cloudy", "weather", "sun"] },
      { emoji: "🌦️", name: "sun behind rain cloud", keywords: ["rain", "sun", "weather", "shower"] },
      { emoji: "🌧️", name: "cloud with rain", keywords: ["rain", "cloud", "weather", "rainy"] },
      { emoji: "🌨️", name: "cloud with snow", keywords: ["snow", "cloud", "weather", "winter"] },
      { emoji: "🌩️", name: "cloud with lightning", keywords: ["lightning", "thunder", "storm", "cloud"] },
      { emoji: "🌪️", name: "tornado", keywords: ["tornado", "wind", "storm", "twister"] },
      { emoji: "🌫️", name: "fog", keywords: ["fog", "mist", "haze", "weather"] },
      { emoji: "🌬️", name: "wind face", keywords: ["wind", "blow", "breeze", "air"] },
      { emoji: "🌀", name: "cyclone", keywords: ["cyclone", "spiral", "hurricane", "typhoon"] },
      { emoji: "🌈", name: "rainbow", keywords: ["rainbow", "colorful", "pride", "hope", "sky"] },
      { emoji: "🌂", name: "closed umbrella", keywords: ["umbrella", "rain", "closed", "weather"] },
      { emoji: "☂️", name: "umbrella", keywords: ["umbrella", "rain", "open", "weather"] },
      { emoji: "☔", name: "umbrella with rain drops", keywords: ["umbrella", "rain", "drops", "weather"] },
      { emoji: "⛱️", name: "umbrella on ground", keywords: ["beach", "umbrella", "sand", "sun"] },
      { emoji: "⚡", name: "high voltage", keywords: ["lightning", "zap", "electric", "fast", "energy"] },
      { emoji: "❄️", name: "snowflake", keywords: ["snow", "cold", "ice", "winter", "frozen"] },
      { emoji: "☃️", name: "snowman", keywords: ["snowman", "snow", "winter", "cold"] },
      { emoji: "⛄", name: "snowman without snow", keywords: ["snowman", "winter", "cold"] },
      { emoji: "☄️", name: "comet", keywords: ["comet", "space", "sky", "asteroid"] },
      { emoji: "🔥", name: "fire", keywords: ["fire", "hot", "flame", "lit", "burn", "trending"] },
      { emoji: "💧", name: "droplet", keywords: ["water", "drop", "rain", "blue", "sweat"] },
      { emoji: "🌊", name: "water wave", keywords: ["wave", "ocean", "surf", "water", "sea"] },
      { emoji: "🌋", name: "volcano", keywords: ["volcano", "mountain", "eruption", "lava"] },
      { emoji: "🏔️", name: "snow-capped mountain", keywords: ["mountain", "snow", "peak", "nature"] },
      { emoji: "⛰️", name: "mountain", keywords: ["mountain", "peak", "nature", "hike"] },
      { emoji: "🗻", name: "mount fuji", keywords: ["fuji", "japan", "mountain", "snow"] },
      { emoji: "🏕️", name: "camping", keywords: ["camping", "camp", "tent", "outdoors"] },
      { emoji: "🏜️", name: "desert", keywords: ["desert", "sand", "hot", "dry", "cactus"] },
      { emoji: "🏝️", name: "desert island", keywords: ["island", "tropical", "beach", "stranded"] },
      { emoji: "🌍", name: "globe showing europe-africa", keywords: ["earth", "globe", "world", "europe", "africa"] },
      { emoji: "🌎", name: "globe showing americas", keywords: ["earth", "globe", "world", "america"] },
      { emoji: "🌏", name: "globe showing asia-australia", keywords: ["earth", "globe", "world", "asia", "australia"] },
      { emoji: "🌐", name: "globe with meridians", keywords: ["earth", "globe", "internet", "world", "web"] },
    ],
  },
  {
    id: "food",
    label: "Food & Drink",
    icon: "🍕",
    emojis: [
      { emoji: "🍎", name: "red apple", keywords: ["apple", "fruit", "red", "food"] },
      { emoji: "🍊", name: "tangerine", keywords: ["orange", "tangerine", "fruit", "citrus"] },
      { emoji: "🍋", name: "lemon", keywords: ["lemon", "citrus", "sour", "fruit", "yellow"] },
      { emoji: "🍇", name: "grapes", keywords: ["grapes", "fruit", "wine", "purple"] },
      { emoji: "🍉", name: "watermelon", keywords: ["watermelon", "fruit", "summer", "red", "green"] },
      { emoji: "🍓", name: "strawberry", keywords: ["strawberry", "fruit", "red", "sweet"] },
      { emoji: "🫐", name: "blueberries", keywords: ["blueberry", "fruit", "blue", "antioxidant"] },
      { emoji: "🍒", name: "cherries", keywords: ["cherry", "fruit", "red", "sweet"] },
      { emoji: "🍑", name: "peach", keywords: ["peach", "fruit", "sweet", "yellow"] },
      { emoji: "🥭", name: "mango", keywords: ["mango", "fruit", "tropical", "sweet"] },
      { emoji: "🍍", name: "pineapple", keywords: ["pineapple", "tropical", "fruit", "yellow"] },
      { emoji: "🥝", name: "kiwi fruit", keywords: ["kiwi", "fruit", "green", "nz"] },
      { emoji: "🍅", name: "tomato", keywords: ["tomato", "red", "vegetable", "sauce"] },
      { emoji: "🫒", name: "olive", keywords: ["olive", "italian", "mediterranean", "fruit"] },
      { emoji: "🥑", name: "avocado", keywords: ["avocado", "guacamole", "green", "healthy"] },
      { emoji: "🍆", name: "eggplant", keywords: ["eggplant", "aubergine", "purple", "vegetable"] },
      { emoji: "🥦", name: "broccoli", keywords: ["broccoli", "vegetable", "green", "healthy"] },
      { emoji: "🥕", name: "carrot", keywords: ["carrot", "vegetable", "orange", "healthy"] },
      { emoji: "🌽", name: "ear of corn", keywords: ["corn", "maize", "vegetable", "yellow"] },
      { emoji: "🫑", name: "bell pepper", keywords: ["pepper", "vegetable", "capsicum"] },
      { emoji: "🥒", name: "cucumber", keywords: ["cucumber", "vegetable", "green", "cool"] },
      { emoji: "🥬", name: "leafy green", keywords: ["salad", "lettuce", "vegetable", "green"] },
      { emoji: "🧅", name: "onion", keywords: ["onion", "vegetable", "tears", "cooking"] },
      { emoji: "🧄", name: "garlic", keywords: ["garlic", "spice", "cooking", "vampire"] },
      { emoji: "🥜", name: "peanuts", keywords: ["peanut", "nut", "snack", "peanut butter"] },
      { emoji: "🫘", name: "beans", keywords: ["beans", "legume", "food", "protein"] },
      { emoji: "🍞", name: "bread", keywords: ["bread", "toast", "carbs", "loaf"] },
      { emoji: "🥐", name: "croissant", keywords: ["croissant", "pastry", "french", "breakfast"] },
      { emoji: "🥖", name: "baguette bread", keywords: ["baguette", "french", "bread", "long"] },
      { emoji: "🫓", name: "flatbread", keywords: ["flatbread", "pita", "bread", "wrap"] },
      { emoji: "🥨", name: "pretzel", keywords: ["pretzel", "salty", "snack", "baked"] },
      { emoji: "🥯", name: "bagel", keywords: ["bagel", "bread", "new york", "breakfast"] },
      { emoji: "🧀", name: "cheese wedge", keywords: ["cheese", "dairy", "cheddar", "food"] },
      { emoji: "🥚", name: "egg", keywords: ["egg", "breakfast", "food", "protein"] },
      { emoji: "🍳", name: "cooking", keywords: ["cooking", "frying", "egg", "pan", "breakfast"] },
      { emoji: "🧈", name: "butter", keywords: ["butter", "dairy", "fat", "spread"] },
      { emoji: "🥞", name: "pancakes", keywords: ["pancakes", "breakfast", "stack", "maple syrup"] },
      { emoji: "🧇", name: "waffle", keywords: ["waffle", "breakfast", "sweet", "syrup"] },
      { emoji: "🥓", name: "bacon", keywords: ["bacon", "breakfast", "pork", "meat", "crispy"] },
      { emoji: "🥩", name: "cut of meat", keywords: ["steak", "meat", "beef", "protein"] },
      { emoji: "🍗", name: "poultry leg", keywords: ["chicken", "drumstick", "turkey", "meat"] },
      { emoji: "🍖", name: "meat on bone", keywords: ["meat", "bone", "ribs", "pork"] },
      { emoji: "🌭", name: "hot dog", keywords: ["hot dog", "sausage", "fast food", "american"] },
      { emoji: "🍔", name: "hamburger", keywords: ["burger", "hamburger", "fast food", "beef"] },
      { emoji: "🍟", name: "french fries", keywords: ["fries", "fast food", "potato", "mcdonalds"] },
      { emoji: "🍕", name: "pizza", keywords: ["pizza", "italian", "cheese", "fast food"] },
      { emoji: "🫔", name: "tamale", keywords: ["tamale", "mexican", "food", "corn"] },
      { emoji: "🌮", name: "taco", keywords: ["taco", "mexican", "food", "crunchy"] },
      { emoji: "🌯", name: "burrito", keywords: ["burrito", "mexican", "wrap", "food"] },
      { emoji: "🥙", name: "stuffed flatbread", keywords: ["pita", "gyro", "wrap", "stuffed"] },
      { emoji: "🧆", name: "falafel", keywords: ["falafel", "middle eastern", "veggie", "chickpea"] },
      { emoji: "🥗", name: "green salad", keywords: ["salad", "healthy", "vegetable", "greens"] },
      { emoji: "🥘", name: "shallow pan of food", keywords: ["paella", "stew", "food", "cook"] },
      { emoji: "🫕", name: "fondue", keywords: ["fondue", "cheese", "chocolate", "pot"] },
      { emoji: "🍝", name: "spaghetti", keywords: ["pasta", "spaghetti", "italian", "food"] },
      { emoji: "🍜", name: "steaming bowl", keywords: ["noodles", "ramen", "soup", "asian", "bowl"] },
      { emoji: "🍲", name: "pot of food", keywords: ["stew", "soup", "pot", "hot", "food"] },
      { emoji: "🍛", name: "curry rice", keywords: ["curry", "rice", "indian", "asian"] },
      { emoji: "🍣", name: "sushi", keywords: ["sushi", "japanese", "fish", "rice", "asian"] },
      { emoji: "🍱", name: "bento box", keywords: ["bento", "japanese", "box", "lunch", "meal"] },
      { emoji: "🥟", name: "dumpling", keywords: ["dumpling", "gyoza", "dim sum", "asian", "chinese"] },
      { emoji: "🦪", name: "oyster", keywords: ["oyster", "shellfish", "seafood", "pearl"] },
      { emoji: "🍦", name: "soft ice cream", keywords: ["ice cream", "soft serve", "dessert", "cold", "sweet"] },
      { emoji: "🍧", name: "shaved ice", keywords: ["shaved ice", "dessert", "cold", "sweet"] },
      { emoji: "🍨", name: "ice cream", keywords: ["ice cream", "dessert", "cold", "sweet"] },
      { emoji: "🍩", name: "doughnut", keywords: ["donut", "doughnut", "dessert", "sweet", "fried"] },
      { emoji: "🍪", name: "cookie", keywords: ["cookie", "dessert", "sweet", "baked", "chocolate chip"] },
      { emoji: "🎂", name: "birthday cake", keywords: ["birthday", "cake", "celebrate", "candles"] },
      { emoji: "🍰", name: "shortcake", keywords: ["cake", "dessert", "slice", "sweet"] },
      { emoji: "🧁", name: "cupcake", keywords: ["cupcake", "dessert", "sweet", "baked", "frosting"] },
      { emoji: "🥧", name: "pie", keywords: ["pie", "dessert", "baked", "sweet"] },
      { emoji: "🍫", name: "chocolate bar", keywords: ["chocolate", "candy", "sweet", "bar"] },
      { emoji: "🍬", name: "candy", keywords: ["candy", "sweet", "sugar", "lollipop"] },
      { emoji: "🍭", name: "lollipop", keywords: ["lollipop", "candy", "sweet", "sugar"] },
      { emoji: "🍮", name: "custard", keywords: ["custard", "flan", "dessert", "pudding"] },
      { emoji: "🍯", name: "honey pot", keywords: ["honey", "sweet", "pot", "jar", "bee"] },
      { emoji: "☕", name: "hot beverage", keywords: ["coffee", "hot", "tea", "cafe", "morning"] },
      { emoji: "🫖", name: "teapot", keywords: ["tea", "pot", "herbal", "drink"] },
      { emoji: "🍵", name: "teacup without handle", keywords: ["tea", "green tea", "japanese", "hot"] },
      { emoji: "🧃", name: "beverage box", keywords: ["juice", "box", "drink", "child"] },
      { emoji: "🥤", name: "cup with straw", keywords: ["soda", "smoothie", "drink", "straw", "cup"] },
      { emoji: "🧋", name: "bubble tea", keywords: ["bubble tea", "boba", "taiwanese", "drink"] },
      { emoji: "🍶", name: "sake", keywords: ["sake", "japanese", "drink", "rice wine"] },
      { emoji: "🍺", name: "beer mug", keywords: ["beer", "drink", "alcohol", "cheers", "pub"] },
      { emoji: "🍻", name: "clinking beer mugs", keywords: ["cheers", "beer", "toast", "celebrate", "drink"] },
      { emoji: "🥂", name: "clinking glasses", keywords: ["cheers", "toast", "celebrate", "wine", "champagne"] },
      { emoji: "🍷", name: "wine glass", keywords: ["wine", "red wine", "alcohol", "drink"] },
      { emoji: "🥃", name: "tumbler glass", keywords: ["whiskey", "bourbon", "drink", "scotch", "spirits"] },
      { emoji: "🍸", name: "cocktail glass", keywords: ["martini", "cocktail", "drink", "alcohol"] },
      { emoji: "🍹", name: "tropical drink", keywords: ["tropical", "cocktail", "drink", "beach", "summer"] },
      { emoji: "🧉", name: "mate", keywords: ["mate", "south american", "drink", "herbal"] },
      { emoji: "🍾", name: "bottle with popping cork", keywords: ["champagne", "celebrate", "pop", "party"] },
    ],
  },
  {
    id: "travel",
    label: "Travel & Places",
    icon: "✈️",
    emojis: [
      { emoji: "🚗", name: "automobile", keywords: ["car", "drive", "vehicle", "auto"] },
      { emoji: "🚕", name: "taxi", keywords: ["taxi", "cab", "car", "ride"] },
      { emoji: "🚙", name: "sport utility vehicle", keywords: ["suv", "car", "vehicle", "drive"] },
      { emoji: "🚌", name: "bus", keywords: ["bus", "transport", "school", "public"] },
      { emoji: "🚎", name: "trolleybus", keywords: ["trolleybus", "transport", "city"] },
      { emoji: "🏎️", name: "racing car", keywords: ["car", "race", "fast", "formula", "sport"] },
      { emoji: "🚓", name: "police car", keywords: ["police", "cop", "car", "law"] },
      { emoji: "🚑", name: "ambulance", keywords: ["ambulance", "emergency", "hospital", "medical"] },
      { emoji: "🚒", name: "fire engine", keywords: ["fire truck", "emergency", "firefighter"] },
      { emoji: "🚐", name: "minibus", keywords: ["van", "minibus", "transport", "vehicle"] },
      { emoji: "🛻", name: "pickup truck", keywords: ["truck", "pickup", "vehicle", "country"] },
      { emoji: "🚚", name: "delivery truck", keywords: ["truck", "delivery", "moving", "transport"] },
      { emoji: "🚛", name: "articulated lorry", keywords: ["truck", "semi", "18 wheeler", "lorry"] },
      { emoji: "🚜", name: "tractor", keywords: ["tractor", "farm", "vehicle", "agriculture"] },
      { emoji: "🏍️", name: "motorcycle", keywords: ["motorcycle", "motorbike", "bike", "ride"] },
      { emoji: "🛵", name: "motor scooter", keywords: ["scooter", "moped", "ride", "vespa"] },
      { emoji: "🚲", name: "bicycle", keywords: ["bicycle", "bike", "cycle", "ride", "sport"] },
      { emoji: "🛴", name: "kick scooter", keywords: ["scooter", "kick", "ride", "urban"] },
      { emoji: "🛹", name: "skateboard", keywords: ["skateboard", "skate", "sport", "cool"] },
      { emoji: "🛼", name: "roller skate", keywords: ["roller", "skate", "rink", "retro"] },
      { emoji: "🚁", name: "helicopter", keywords: ["helicopter", "fly", "aviation", "rotor"] },
      { emoji: "🛸", name: "flying saucer", keywords: ["ufo", "alien", "space", "fly", "saucer"] },
      { emoji: "✈️", name: "airplane", keywords: ["plane", "fly", "travel", "airport", "aviation"] },
      { emoji: "🛩️", name: "small airplane", keywords: ["plane", "small", "fly", "private"] },
      { emoji: "🚀", name: "rocket", keywords: ["rocket", "space", "launch", "fast", "startup"] },
      { emoji: "💺", name: "seat", keywords: ["seat", "chair", "airline", "plane"] },
      { emoji: "🛶", name: "canoe", keywords: ["canoe", "kayak", "boat", "paddle", "water"] },
      { emoji: "⛵", name: "sailboat", keywords: ["sail", "boat", "sea", "wind", "yacht"] },
      { emoji: "🚤", name: "speedboat", keywords: ["speedboat", "boat", "fast", "water", "wave"] },
      { emoji: "🛥️", name: "motor boat", keywords: ["motorboat", "boat", "water", "speed"] },
      { emoji: "🚢", name: "ship", keywords: ["ship", "cruise", "ocean", "boat", "sea"] },
      { emoji: "⚓", name: "anchor", keywords: ["anchor", "ship", "harbor", "marina", "navy"] },
      { emoji: "🗺️", name: "world map", keywords: ["map", "world", "travel", "geography", "navigate"] },
      { emoji: "🧭", name: "compass", keywords: ["compass", "navigate", "direction", "north", "explore"] },
      { emoji: "🌋", name: "volcano", keywords: ["volcano", "mountain", "eruption", "lava", "hot"] },
      { emoji: "🗾", name: "map of japan", keywords: ["japan", "map", "island", "asia"] },
      { emoji: "🏔️", name: "snow-capped mountain", keywords: ["mountain", "snow", "peak", "hiking"] },
      { emoji: "⛰️", name: "mountain", keywords: ["mountain", "peak", "hike", "nature"] },
      { emoji: "🏕️", name: "camping", keywords: ["camping", "tent", "outdoor", "nature", "wilderness"] },
      { emoji: "🏖️", name: "beach with umbrella", keywords: ["beach", "vacation", "summer", "sand", "ocean"] },
      { emoji: "🏜️", name: "desert", keywords: ["desert", "sand", "dry", "hot", "cactus"] },
      { emoji: "🏗️", name: "building construction", keywords: ["construction", "building", "crane", "work"] },
      { emoji: "🏘️", name: "houses", keywords: ["houses", "neighborhood", "home", "suburb"] },
      { emoji: "🏚️", name: "derelict house", keywords: ["abandoned", "house", "haunted", "ruin"] },
      { emoji: "🏠", name: "house", keywords: ["house", "home", "building", "neighborhood"] },
      { emoji: "🏡", name: "house with garden", keywords: ["house", "garden", "home", "suburb"] },
      { emoji: "🏢", name: "office building", keywords: ["office", "building", "work", "business"] },
      { emoji: "🏣", name: "japanese post office", keywords: ["post office", "japanese", "mail"] },
      { emoji: "🏤", name: "post office", keywords: ["post office", "mail", "building"] },
      { emoji: "🏥", name: "hospital", keywords: ["hospital", "medical", "health", "emergency"] },
      { emoji: "🏦", name: "bank", keywords: ["bank", "money", "finance", "building"] },
      { emoji: "🏨", name: "hotel", keywords: ["hotel", "travel", "stay", "accommodation"] },
      { emoji: "🏩", name: "love hotel", keywords: ["love hotel", "romance", "pink"] },
      { emoji: "🏪", name: "convenience store", keywords: ["store", "shop", "convenience", "7-11"] },
      { emoji: "🏫", name: "school", keywords: ["school", "education", "learn", "building"] },
      { emoji: "🏬", name: "department store", keywords: ["mall", "store", "shopping", "department"] },
      { emoji: "🏭", name: "factory", keywords: ["factory", "industry", "building", "manufacture"] },
      { emoji: "🏯", name: "japanese castle", keywords: ["castle", "japan", "historic", "fortress"] },
      { emoji: "🏰", name: "castle", keywords: ["castle", "medieval", "kingdom", "fairy tale"] },
      { emoji: "💒", name: "wedding", keywords: ["wedding", "chapel", "church", "marriage"] },
      { emoji: "🗼", name: "tokyo tower", keywords: ["tower", "tokyo", "japan", "landmark"] },
      { emoji: "🗽", name: "statue of liberty", keywords: ["statue", "liberty", "new york", "usa", "landmark"] },
      { emoji: "⛪", name: "church", keywords: ["church", "religion", "christian", "cross", "pray"] },
      { emoji: "🕌", name: "mosque", keywords: ["mosque", "islam", "religion", "muslim"] },
      { emoji: "🛕", name: "hindu temple", keywords: ["temple", "hindu", "religion", "india"] },
      { emoji: "🕍", name: "synagogue", keywords: ["synagogue", "jewish", "religion", "star of david"] },
      { emoji: "⛩️", name: "shinto shrine", keywords: ["shrine", "japanese", "shinto", "torii"] },
      { emoji: "🗿", name: "moai", keywords: ["moai", "easter island", "statue", "rock"] },
      { emoji: "🌁", name: "foggy", keywords: ["fog", "mist", "bridge", "city", "morning"] },
      { emoji: "🌃", name: "night with stars", keywords: ["night", "city", "stars", "urban"] },
      { emoji: "🏙️", name: "cityscape", keywords: ["city", "skyline", "urban", "downtown"] },
      { emoji: "🌄", name: "sunrise over mountains", keywords: ["sunrise", "mountain", "morning", "dawn"] },
      { emoji: "🌅", name: "sunrise", keywords: ["sunrise", "morning", "dawn", "sun", "sky"] },
      { emoji: "🌆", name: "cityscape at dusk", keywords: ["city", "dusk", "sunset", "urban"] },
      { emoji: "🌇", name: "sunset", keywords: ["sunset", "city", "evening", "orange", "sky"] },
      { emoji: "🌉", name: "bridge at night", keywords: ["bridge", "night", "city", "lights"] },
      { emoji: "🎠", name: "carousel horse", keywords: ["carousel", "horse", "fair", "amusement park"] },
      { emoji: "🛝", name: "playground slide", keywords: ["slide", "playground", "kids", "park"] },
      { emoji: "🎡", name: "ferris wheel", keywords: ["ferris wheel", "fair", "amusement", "carnival"] },
      { emoji: "🎢", name: "roller coaster", keywords: ["roller coaster", "thrill", "amusement", "fun"] },
    ],
  },
  {
    id: "activities",
    label: "Activities",
    icon: "⚽",
    emojis: [
      { emoji: "⚽", name: "soccer ball", keywords: ["soccer", "football", "sport", "ball"] },
      { emoji: "🏀", name: "basketball", keywords: ["basketball", "sport", "ball", "nba"] },
      { emoji: "🏈", name: "american football", keywords: ["football", "nfl", "sport", "ball"] },
      { emoji: "⚾", name: "baseball", keywords: ["baseball", "sport", "ball", "mlb"] },
      { emoji: "🥎", name: "softball", keywords: ["softball", "sport", "ball"] },
      { emoji: "🎾", name: "tennis", keywords: ["tennis", "sport", "ball", "racket"] },
      { emoji: "🏐", name: "volleyball", keywords: ["volleyball", "sport", "ball", "beach"] },
      { emoji: "🏉", name: "rugby football", keywords: ["rugby", "sport", "ball", "oval"] },
      { emoji: "🥏", name: "flying disc", keywords: ["frisbee", "disc", "throw", "sport"] },
      { emoji: "🎱", name: "pool 8 ball", keywords: ["billiards", "pool", "eight ball", "sport"] },
      { emoji: "🏓", name: "ping pong", keywords: ["ping pong", "table tennis", "sport", "paddle"] },
      { emoji: "🏸", name: "badminton", keywords: ["badminton", "shuttlecock", "sport", "racket"] },
      { emoji: "🏒", name: "ice hockey", keywords: ["hockey", "ice", "sport", "stick", "puck"] },
      { emoji: "🏑", name: "field hockey", keywords: ["hockey", "field", "sport", "stick"] },
      { emoji: "🏏", name: "cricket game", keywords: ["cricket", "sport", "bat", "ball"] },
      { emoji: "🏹", name: "bow and arrow", keywords: ["archery", "bow", "arrow", "sport"] },
      { emoji: "🎣", name: "fishing pole", keywords: ["fishing", "fish", "pole", "hobby"] },
      { emoji: "🤿", name: "diving mask", keywords: ["diving", "snorkel", "swim", "ocean"] },
      { emoji: "🎿", name: "skis", keywords: ["skiing", "ski", "snow", "winter", "sport"] },
      { emoji: "🛷", name: "sled", keywords: ["sled", "snow", "winter", "sledge"] },
      { emoji: "🥅", name: "goal net", keywords: ["goal", "net", "soccer", "hockey", "sport"] },
      { emoji: "🎯", name: "bullseye", keywords: ["target", "goal", "aim", "dart", "bullseye"] },
      { emoji: "🎮", name: "video game", keywords: ["game", "controller", "gaming", "console", "play"] },
      { emoji: "🕹️", name: "joystick", keywords: ["joystick", "game", "arcade", "control"] },
      { emoji: "🎲", name: "game die", keywords: ["dice", "game", "luck", "random", "roll"] },
      { emoji: "🧩", name: "puzzle piece", keywords: ["puzzle", "piece", "jigsaw", "fit"] },
      { emoji: "🎭", name: "performing arts", keywords: ["theater", "mask", "drama", "performance"] },
      { emoji: "🎨", name: "artist palette", keywords: ["art", "paint", "creative", "palette", "artist"] },
      { emoji: "🎬", name: "clapper board", keywords: ["movie", "film", "action", "cinema", "director"] },
      { emoji: "🎤", name: "microphone", keywords: ["mic", "sing", "karaoke", "music", "perform"] },
      { emoji: "🎧", name: "headphone", keywords: ["headphones", "music", "listen", "audio"] },
      { emoji: "🎼", name: "musical score", keywords: ["music", "notes", "sheet music", "composer"] },
      { emoji: "🎵", name: "musical note", keywords: ["music", "note", "song", "sound"] },
      { emoji: "🎶", name: "musical notes", keywords: ["music", "notes", "song", "melody"] },
      { emoji: "🎸", name: "guitar", keywords: ["guitar", "music", "rock", "instrument"] },
      { emoji: "🎹", name: "musical keyboard", keywords: ["piano", "keyboard", "music", "keys"] },
      { emoji: "🎺", name: "trumpet", keywords: ["trumpet", "music", "jazz", "instrument", "brass"] },
      { emoji: "🎻", name: "violin", keywords: ["violin", "music", "classical", "instrument", "strings"] },
      { emoji: "🪕", name: "banjo", keywords: ["banjo", "country", "music", "bluegrass", "instrument"] },
      { emoji: "🥁", name: "drum", keywords: ["drum", "music", "beat", "percussion", "rhythm"] },
      { emoji: "🪘", name: "long drum", keywords: ["conga", "drum", "music", "percussion"] },
      { emoji: "🎷", name: "saxophone", keywords: ["saxophone", "sax", "jazz", "music", "instrument"] },
      { emoji: "🪗", name: "accordion", keywords: ["accordion", "music", "instrument", "folk"] },
      { emoji: "🎙️", name: "studio microphone", keywords: ["mic", "studio", "record", "podcast", "broadcast"] },
      { emoji: "📻", name: "radio", keywords: ["radio", "broadcast", "music", "station", "retro"] },
      { emoji: "🎞️", name: "film frames", keywords: ["film", "movie", "cinema", "reel", "old"] },
      { emoji: "📽️", name: "film projector", keywords: ["projector", "movie", "cinema", "film"] },
      { emoji: "🎪", name: "circus tent", keywords: ["circus", "tent", "carnival", "performance"] },
      { emoji: "🎠", name: "carousel horse", keywords: ["carousel", "horse", "fair", "ride"] },
      { emoji: "🎡", name: "ferris wheel", keywords: ["ferris wheel", "carnival", "fair", "ride"] },
      { emoji: "🎢", name: "roller coaster", keywords: ["roller coaster", "thrill", "amusement", "fun"] },
      { emoji: "🏆", name: "trophy", keywords: ["trophy", "win", "award", "champion", "gold"] },
      { emoji: "🥇", name: "1st place medal", keywords: ["gold", "medal", "first", "winner", "champion"] },
      { emoji: "🥈", name: "2nd place medal", keywords: ["silver", "medal", "second"] },
      { emoji: "🥉", name: "3rd place medal", keywords: ["bronze", "medal", "third"] },
      { emoji: "🏅", name: "sports medal", keywords: ["medal", "sport", "award", "win"] },
      { emoji: "🎖️", name: "military medal", keywords: ["medal", "military", "award", "honor"] },
      { emoji: "🎗️", name: "reminder ribbon", keywords: ["ribbon", "award", "awareness", "cause"] },
      { emoji: "🎫", name: "ticket", keywords: ["ticket", "event", "concert", "movie", "admit"] },
      { emoji: "🎟️", name: "admission tickets", keywords: ["tickets", "event", "concert", "admit"] },
      { emoji: "🎪", name: "circus tent", keywords: ["circus", "tent", "show", "carnival"] },
      { emoji: "🤹", name: "person juggling", keywords: ["juggle", "skill", "circus", "performance"] },
    ],
  },
  {
    id: "objects",
    label: "Objects",
    icon: "💡",
    emojis: [
      { emoji: "⌚", name: "watch", keywords: ["watch", "time", "clock", "wrist"] },
      { emoji: "📱", name: "mobile phone", keywords: ["phone", "mobile", "cell", "iphone", "smartphone"] },
      { emoji: "📲", name: "mobile phone with arrow", keywords: ["phone", "call", "mobile", "incoming"] },
      { emoji: "💻", name: "laptop", keywords: ["laptop", "computer", "macbook", "pc", "tech"] },
      { emoji: "⌨️", name: "keyboard", keywords: ["keyboard", "type", "computer", "input"] },
      { emoji: "🖥️", name: "desktop computer", keywords: ["computer", "desktop", "monitor", "pc"] },
      { emoji: "🖨️", name: "printer", keywords: ["printer", "print", "office", "document"] },
      { emoji: "🖱️", name: "computer mouse", keywords: ["mouse", "cursor", "click", "computer"] },
      { emoji: "🖲️", name: "trackball", keywords: ["trackball", "mouse", "computer", "input"] },
      { emoji: "💽", name: "computer disk", keywords: ["disk", "minidisc", "storage", "data"] },
      { emoji: "💾", name: "floppy disk", keywords: ["floppy", "disk", "save", "retro", "storage"] },
      { emoji: "💿", name: "optical disk", keywords: ["cd", "dvd", "disk", "music", "data"] },
      { emoji: "📀", name: "dvd", keywords: ["dvd", "disk", "movie", "data", "disc"] },
      { emoji: "🧮", name: "abacus", keywords: ["abacus", "calculate", "math", "bead"] },
      { emoji: "📷", name: "camera", keywords: ["camera", "photo", "picture", "photography"] },
      { emoji: "📸", name: "camera with flash", keywords: ["camera", "flash", "photo", "picture", "selfie"] },
      { emoji: "📹", name: "video camera", keywords: ["video", "camera", "film", "record"] },
      { emoji: "🎥", name: "movie camera", keywords: ["movie", "camera", "film", "cinema"] },
      { emoji: "📽️", name: "film projector", keywords: ["projector", "film", "movie", "cinema"] },
      { emoji: "📡", name: "satellite antenna", keywords: ["satellite", "dish", "signal", "broadcast"] },
      { emoji: "📺", name: "television", keywords: ["tv", "television", "watch", "screen", "media"] },
      { emoji: "📻", name: "radio", keywords: ["radio", "music", "broadcast", "station"] },
      { emoji: "🧭", name: "compass", keywords: ["compass", "direction", "navigate", "north"] },
      { emoji: "⏱️", name: "stopwatch", keywords: ["stopwatch", "time", "timer", "clock"] },
      { emoji: "⏲️", name: "timer clock", keywords: ["timer", "clock", "countdown", "time"] },
      { emoji: "⏰", name: "alarm clock", keywords: ["alarm", "clock", "wake", "morning", "time"] },
      { emoji: "🕰️", name: "mantelpiece clock", keywords: ["clock", "time", "antique", "mantle"] },
      { emoji: "⌛", name: "hourglass done", keywords: ["hourglass", "time", "done", "sand", "wait"] },
      { emoji: "⏳", name: "hourglass not done", keywords: ["hourglass", "time", "sand", "wait", "loading"] },
      { emoji: "📡", name: "satellite", keywords: ["satellite", "space", "signal", "dish"] },
      { emoji: "🔋", name: "battery", keywords: ["battery", "charge", "energy", "power", "electric"] },
      { emoji: "🪫", name: "low battery", keywords: ["battery", "low", "empty", "dying", "power"] },
      { emoji: "🔌", name: "electric plug", keywords: ["plug", "power", "electric", "charge"] },
      { emoji: "💡", name: "light bulb", keywords: ["bulb", "light", "idea", "bright", "electric"] },
      { emoji: "🔦", name: "flashlight", keywords: ["flashlight", "torch", "light", "dark"] },
      { emoji: "🕯️", name: "candle", keywords: ["candle", "light", "flame", "wax", "birthday"] },
      { emoji: "🪔", name: "diya lamp", keywords: ["lamp", "diya", "diwali", "oil", "light"] },
      { emoji: "🧯", name: "fire extinguisher", keywords: ["fire", "extinguisher", "safety", "emergency"] },
      { emoji: "🛢️", name: "oil drum", keywords: ["oil", "drum", "barrel", "fuel"] },
      { emoji: "💰", name: "money bag", keywords: ["money", "bag", "rich", "cash", "wealth"] },
      { emoji: "🪙", name: "coin", keywords: ["coin", "money", "currency", "gold", "token"] },
      { emoji: "💳", name: "credit card", keywords: ["credit card", "debit", "money", "pay", "bank"] },
      { emoji: "💴", name: "yen banknote", keywords: ["yen", "money", "japan", "currency"] },
      { emoji: "💵", name: "dollar banknote", keywords: ["dollar", "money", "usd", "american", "cash"] },
      { emoji: "💶", name: "euro banknote", keywords: ["euro", "money", "europe", "currency"] },
      { emoji: "💷", name: "pound banknote", keywords: ["pound", "money", "uk", "british", "currency"] },
      { emoji: "💸", name: "money with wings", keywords: ["money", "spending", "fly", "expensive", "waste"] },
      { emoji: "📊", name: "bar chart", keywords: ["chart", "graph", "bar", "data", "analytics"] },
      { emoji: "📈", name: "chart increasing", keywords: ["chart", "up", "growth", "trending", "profit"] },
      { emoji: "📉", name: "chart decreasing", keywords: ["chart", "down", "loss", "decline"] },
      { emoji: "🗂️", name: "card index dividers", keywords: ["folder", "tabs", "organize", "files"] },
      { emoji: "📁", name: "file folder", keywords: ["folder", "file", "directory", "organize"] },
      { emoji: "📂", name: "open file folder", keywords: ["folder", "open", "file", "directory"] },
      { emoji: "🗃️", name: "card file box", keywords: ["files", "archive", "storage", "organize"] },
      { emoji: "📋", name: "clipboard", keywords: ["clipboard", "list", "notes", "paper"] },
      { emoji: "📌", name: "pushpin", keywords: ["pin", "push pin", "map", "location", "bookmark"] },
      { emoji: "📍", name: "round pushpin", keywords: ["pin", "location", "map", "place"] },
      { emoji: "📎", name: "paperclip", keywords: ["paperclip", "attach", "clip", "paper"] },
      { emoji: "🖇️", name: "linked paperclips", keywords: ["paperclip", "link", "attach", "chain"] },
      { emoji: "📏", name: "straight ruler", keywords: ["ruler", "measure", "straight", "length"] },
      { emoji: "📐", name: "triangular ruler", keywords: ["ruler", "triangle", "measure", "geometry"] },
      { emoji: "✂️", name: "scissors", keywords: ["scissors", "cut", "craft", "snip"] },
      { emoji: "🗃️", name: "card file box", keywords: ["box", "files", "archive", "storage"] },
      { emoji: "🗑️", name: "wastebasket", keywords: ["trash", "delete", "garbage", "bin", "waste"] },
      { emoji: "🔒", name: "locked", keywords: ["lock", "secure", "closed", "private", "password"] },
      { emoji: "🔓", name: "unlocked", keywords: ["unlock", "open", "unsecured", "free"] },
      { emoji: "🔐", name: "locked with key", keywords: ["locked", "key", "secure", "safe"] },
      { emoji: "🔑", name: "key", keywords: ["key", "unlock", "lock", "password", "access"] },
      { emoji: "🗝️", name: "old key", keywords: ["key", "old", "lock", "vintage"] },
      { emoji: "🔨", name: "hammer", keywords: ["hammer", "tool", "build", "hit"] },
      { emoji: "🪓", name: "axe", keywords: ["axe", "chop", "wood", "tool", "lumberjack"] },
      { emoji: "⛏️", name: "pick", keywords: ["pick", "mine", "tool", "mining"] },
      { emoji: "⚒️", name: "hammer and pick", keywords: ["tools", "build", "mine", "worker"] },
      { emoji: "🛠️", name: "hammer and wrench", keywords: ["tools", "repair", "fix", "build"] },
      { emoji: "🗡️", name: "dagger", keywords: ["dagger", "knife", "blade", "weapon"] },
      { emoji: "⚔️", name: "crossed swords", keywords: ["swords", "fight", "battle", "weapon"] },
      { emoji: "🛡️", name: "shield", keywords: ["shield", "protect", "defense", "guard"] },
      { emoji: "🪚", name: "carpentry saw", keywords: ["saw", "carpenter", "tool", "wood"] },
      { emoji: "🔧", name: "wrench", keywords: ["wrench", "spanner", "tool", "fix", "repair"] },
      { emoji: "🪛", name: "screwdriver", keywords: ["screwdriver", "tool", "fix", "repair"] },
      { emoji: "🔩", name: "nut and bolt", keywords: ["bolt", "nut", "screw", "tool", "metal"] },
      { emoji: "⚙️", name: "gear", keywords: ["gear", "settings", "engine", "cog", "mechanism"] },
      { emoji: "🗜️", name: "clamp", keywords: ["clamp", "tool", "squeeze", "tight"] },
      { emoji: "🔗", name: "link", keywords: ["link", "chain", "connect", "url", "hyperlink"] },
      { emoji: "⛓️", name: "chains", keywords: ["chain", "link", "bind", "locked"] },
      { emoji: "🪝", name: "hook", keywords: ["hook", "hang", "catch", "fish"] },
      { emoji: "🧲", name: "magnet", keywords: ["magnet", "attract", "metal", "horseshoe"] },
      { emoji: "🔭", name: "telescope", keywords: ["telescope", "astronomy", "space", "stars", "science"] },
      { emoji: "🔬", name: "microscope", keywords: ["microscope", "science", "lab", "biology", "research"] },
      { emoji: "🩺", name: "stethoscope", keywords: ["stethoscope", "doctor", "medical", "health", "hospital"] },
      { emoji: "🩻", name: "x-ray", keywords: ["xray", "medical", "skeleton", "bone", "scan"] },
      { emoji: "💊", name: "pill", keywords: ["pill", "medicine", "drug", "prescription", "health"] },
      { emoji: "💉", name: "syringe", keywords: ["syringe", "injection", "vaccine", "medical", "needle"] },
      { emoji: "🩹", name: "adhesive bandage", keywords: ["bandage", "plaster", "boo boo", "hurt", "heal"] },
      { emoji: "🩼", name: "crutch", keywords: ["crutch", "injury", "walking aid", "support"] },
      { emoji: "🩺", name: "stethoscope", keywords: ["stethoscope", "doctor", "heart", "medical"] },
      { emoji: "📦", name: "package", keywords: ["package", "box", "parcel", "delivery", "shipping"] },
      { emoji: "📫", name: "closed mailbox with raised flag", keywords: ["mailbox", "mail", "letter", "post"] },
      { emoji: "📪", name: "closed mailbox with lowered flag", keywords: ["mailbox", "mail", "empty"] },
      { emoji: "📬", name: "open mailbox with raised flag", keywords: ["mailbox", "mail", "open", "letter"] },
      { emoji: "📭", name: "open mailbox with lowered flag", keywords: ["mailbox", "open", "empty"] },
      { emoji: "📮", name: "postbox", keywords: ["post", "mail", "postbox", "letter", "red"] },
      { emoji: "🗳️", name: "ballot box with ballot", keywords: ["vote", "ballot", "election", "democracy"] },
      { emoji: "✏️", name: "pencil", keywords: ["pencil", "write", "edit", "draw", "sketch"] },
      { emoji: "✒️", name: "black nib", keywords: ["pen", "nib", "write", "ink"] },
      { emoji: "🖋️", name: "fountain pen", keywords: ["pen", "fountain", "write", "ink", "fancy"] },
      { emoji: "🖊️", name: "pen", keywords: ["pen", "ballpoint", "write", "ink"] },
      { emoji: "🖌️", name: "paintbrush", keywords: ["brush", "paint", "art", "craft"] },
      { emoji: "🖍️", name: "crayon", keywords: ["crayon", "color", "draw", "kid", "art"] },
      { emoji: "📝", name: "memo", keywords: ["note", "write", "memo", "edit", "list"] },
      { emoji: "📓", name: "notebook", keywords: ["notebook", "book", "notes", "school"] },
      { emoji: "📔", name: "notebook with decorative cover", keywords: ["notebook", "journal", "book", "diary"] },
      { emoji: "📒", name: "ledger", keywords: ["ledger", "book", "account", "notes", "yellow"] },
      { emoji: "📕", name: "closed book", keywords: ["book", "read", "closed", "study"] },
      { emoji: "📗", name: "green book", keywords: ["book", "read", "green", "study"] },
      { emoji: "📘", name: "blue book", keywords: ["book", "read", "blue", "study"] },
      { emoji: "📙", name: "orange book", keywords: ["book", "read", "orange", "study"] },
      { emoji: "📚", name: "books", keywords: ["books", "read", "study", "library", "education"] },
      { emoji: "📖", name: "open book", keywords: ["book", "read", "open", "study", "learn"] },
      { emoji: "🔖", name: "bookmark", keywords: ["bookmark", "save", "mark", "book", "reading"] },
      { emoji: "🏷️", name: "label", keywords: ["label", "tag", "price", "sticker"] },
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    icon: "❤️",
    emojis: [
      { emoji: "❤️", name: "red heart", keywords: ["heart", "love", "red", "like", "romance"] },
      { emoji: "🧡", name: "orange heart", keywords: ["heart", "love", "orange"] },
      { emoji: "💛", name: "yellow heart", keywords: ["heart", "love", "yellow", "friendship"] },
      { emoji: "💚", name: "green heart", keywords: ["heart", "love", "green", "nature"] },
      { emoji: "💙", name: "blue heart", keywords: ["heart", "love", "blue", "calm"] },
      { emoji: "💜", name: "purple heart", keywords: ["heart", "love", "purple", "royalty"] },
      { emoji: "🖤", name: "black heart", keywords: ["heart", "black", "dark", "evil"] },
      { emoji: "🤍", name: "white heart", keywords: ["heart", "white", "pure", "love"] },
      { emoji: "🤎", name: "brown heart", keywords: ["heart", "brown", "love"] },
      { emoji: "💔", name: "broken heart", keywords: ["broken heart", "heartbreak", "sad", "loss"] },
      { emoji: "❤️‍🔥", name: "heart on fire", keywords: ["heart", "fire", "burning", "passion", "love"] },
      { emoji: "❤️‍🩹", name: "mending heart", keywords: ["heart", "heal", "repair", "love", "care"] },
      { emoji: "💕", name: "two hearts", keywords: ["love", "hearts", "two", "affection", "romance"] },
      { emoji: "💞", name: "revolving hearts", keywords: ["hearts", "love", "revolving", "romance"] },
      { emoji: "💓", name: "beating heart", keywords: ["heart", "beating", "love", "pulse"] },
      { emoji: "💗", name: "growing heart", keywords: ["heart", "growing", "love", "pink"] },
      { emoji: "💖", name: "sparkling heart", keywords: ["heart", "sparkling", "love", "pink"] },
      { emoji: "💘", name: "heart with arrow", keywords: ["heart", "arrow", "cupid", "love"] },
      { emoji: "💝", name: "heart with ribbon", keywords: ["heart", "gift", "ribbon", "love"] },
      { emoji: "💟", name: "heart decoration", keywords: ["heart", "purple", "decoration"] },
      { emoji: "☮️", name: "peace symbol", keywords: ["peace", "hippie", "symbol", "love"] },
      { emoji: "✝️", name: "latin cross", keywords: ["cross", "christian", "religion", "church"] },
      { emoji: "☪️", name: "star and crescent", keywords: ["islam", "muslim", "star", "crescent"] },
      { emoji: "🕉️", name: "om", keywords: ["om", "hindu", "peace", "meditation"] },
      { emoji: "☸️", name: "wheel of dharma", keywords: ["dharma", "buddhism", "wheel", "spin"] },
      { emoji: "✡️", name: "star of david", keywords: ["star", "jewish", "judaism", "religion"] },
      { emoji: "🔯", name: "dotted six-pointed star", keywords: ["star", "jewish", "hexagram"] },
      { emoji: "🪯", name: "khanda", keywords: ["sikh", "khanda", "religion"] },
      { emoji: "☯️", name: "yin yang", keywords: ["yin yang", "balance", "harmony", "zen", "taoism"] },
      { emoji: "☦️", name: "orthodox cross", keywords: ["cross", "orthodox", "christian"] },
      { emoji: "🛐", name: "place of worship", keywords: ["pray", "worship", "religion", "church"] },
      { emoji: "🔱", name: "trident emblem", keywords: ["trident", "poseidon", "symbol", "anchor"] },
      { emoji: "📛", name: "name badge", keywords: ["badge", "name", "nametag", "hello"] },
      { emoji: "🔰", name: "japanese symbol for beginner", keywords: ["beginner", "japanese", "green", "symbol"] },
      { emoji: "⭕", name: "hollow red circle", keywords: ["circle", "red", "o", "empty", "symbol"] },
      { emoji: "✅", name: "check mark button", keywords: ["check", "done", "yes", "correct", "ok", "tick"] },
      { emoji: "☑️", name: "check box with check", keywords: ["checkbox", "check", "done", "yes", "tick"] },
      { emoji: "✔️", name: "check mark", keywords: ["check", "yes", "done", "correct", "mark"] },
      { emoji: "❎", name: "cross mark button", keywords: ["cross", "x", "no", "wrong", "error"] },
      { emoji: "❌", name: "cross mark", keywords: ["cross", "x", "no", "wrong", "error", "cancel"] },
      { emoji: "➕", name: "plus", keywords: ["plus", "add", "more", "math"] },
      { emoji: "➖", name: "minus", keywords: ["minus", "subtract", "less", "math"] },
      { emoji: "➗", name: "divide", keywords: ["divide", "division", "math"] },
      { emoji: "✖️", name: "multiply", keywords: ["multiply", "times", "math", "x"] },
      { emoji: "♾️", name: "infinity", keywords: ["infinity", "forever", "loop", "math"] },
      { emoji: "💲", name: "heavy dollar sign", keywords: ["dollar", "money", "sign", "currency"] },
      { emoji: "💱", name: "currency exchange", keywords: ["exchange", "currency", "money", "swap"] },
      { emoji: "™️", name: "trade mark", keywords: ["trademark", "brand", "tm", "registered"] },
      { emoji: "©️", name: "copyright", keywords: ["copyright", "c", "protected", "rights"] },
      { emoji: "®️", name: "registered", keywords: ["registered", "trademark", "brand", "r"] },
      { emoji: "〰️", name: "wavy dash", keywords: ["wave", "dash", "line", "approximately"] },
      { emoji: "➰", name: "curly loop", keywords: ["loop", "curly", "round", "circle"] },
      { emoji: "➿", name: "double curly loop", keywords: ["loop", "double", "curly", "circle"] },
      { emoji: "🔚", name: "end arrow", keywords: ["end", "arrow", "back", "button"] },
      { emoji: "🔛", name: "on arrow", keywords: ["on", "arrow", "button"] },
      { emoji: "🔜", name: "soon arrow", keywords: ["soon", "arrow", "coming"] },
      { emoji: "🔝", name: "top arrow", keywords: ["top", "arrow", "up", "button"] },
      { emoji: "🔙", name: "back arrow", keywords: ["back", "arrow", "return", "previous"] },
      { emoji: "▶️", name: "play button", keywords: ["play", "video", "start", "media"] },
      { emoji: "⏸️", name: "pause button", keywords: ["pause", "media", "stop"] },
      { emoji: "⏹️", name: "stop button", keywords: ["stop", "square", "media"] },
      { emoji: "⏺️", name: "record button", keywords: ["record", "media", "dot", "video"] },
      { emoji: "⏭️", name: "next track button", keywords: ["next", "skip", "media", "forward"] },
      { emoji: "⏮️", name: "last track button", keywords: ["previous", "back", "media", "rewind"] },
      { emoji: "⏩", name: "fast-forward button", keywords: ["fast forward", "skip", "media", "speed"] },
      { emoji: "⏪", name: "fast reverse button", keywords: ["rewind", "back", "media"] },
      { emoji: "🔀", name: "shuffle tracks button", keywords: ["shuffle", "random", "music", "mix"] },
      { emoji: "🔁", name: "repeat button", keywords: ["repeat", "loop", "again", "music"] },
      { emoji: "🔂", name: "repeat single button", keywords: ["repeat", "once", "single", "music"] },
      { emoji: "🔔", name: "bell", keywords: ["bell", "notification", "ring", "alert"] },
      { emoji: "🔕", name: "bell with slash", keywords: ["bell", "mute", "no sound", "silent"] },
      { emoji: "🔇", name: "muted speaker", keywords: ["mute", "no sound", "silent", "speaker"] },
      { emoji: "🔈", name: "speaker low volume", keywords: ["speaker", "low", "quiet", "sound"] },
      { emoji: "🔉", name: "speaker medium volume", keywords: ["speaker", "medium", "sound"] },
      { emoji: "🔊", name: "speaker high volume", keywords: ["speaker", "loud", "sound", "volume"] },
      { emoji: "📣", name: "megaphone", keywords: ["megaphone", "loud", "announce", "cheer"] },
      { emoji: "📢", name: "loudspeaker", keywords: ["announcement", "loud", "speaker", "broadcast"] },
      { emoji: "🔔", name: "bell", keywords: ["bell", "ring", "notification", "sound"] },
      { emoji: "🎵", name: "musical note", keywords: ["music", "note", "song", "sound", "sing"] },
      { emoji: "🎶", name: "musical notes", keywords: ["music", "notes", "melody", "song"] },
      { emoji: "📶", name: "antenna bars", keywords: ["signal", "wifi", "bars", "strength"] },
      { emoji: "📳", name: "vibration mode", keywords: ["vibrate", "phone", "silent", "mode"] },
      { emoji: "📴", name: "mobile phone off", keywords: ["phone", "off", "airplane mode", "power"] },
      { emoji: "♀️", name: "female sign", keywords: ["female", "woman", "gender", "venus"] },
      { emoji: "♂️", name: "male sign", keywords: ["male", "man", "gender", "mars"] },
      { emoji: "⚧️", name: "transgender symbol", keywords: ["transgender", "trans", "gender", "symbol"] },
      { emoji: "🚼", name: "baby symbol", keywords: ["baby", "child", "infant", "diaper"] },
      { emoji: "🚻", name: "restroom", keywords: ["restroom", "bathroom", "toilet", "wc"] },
      { emoji: "🚮", name: "litter in bin sign", keywords: ["litter", "trash", "bin", "recycle"] },
      { emoji: "🚰", name: "potable water", keywords: ["water", "drink", "tap", "fountain"] },
      { emoji: "♿", name: "wheelchair symbol", keywords: ["wheelchair", "accessibility", "disabled", "mobility"] },
      { emoji: "🚹", name: "men's room", keywords: ["men", "bathroom", "restroom", "male"] },
      { emoji: "🚺", name: "women's room", keywords: ["women", "bathroom", "restroom", "female"] },
      { emoji: "🛗", name: "elevator", keywords: ["elevator", "lift", "floors", "up down"] },
      { emoji: "🚷", name: "no pedestrians", keywords: ["no", "walking", "prohibited", "sign"] },
      { emoji: "📵", name: "no mobile phones", keywords: ["no phone", "prohibited", "mobile", "sign"] },
      { emoji: "🔞", name: "no one under eighteen", keywords: ["18", "adult", "restricted", "nsfw"] },
      { emoji: "🔃", name: "clockwise vertical arrows", keywords: ["refresh", "reload", "clockwise", "cycle"] },
      { emoji: "🔄", name: "counterclockwise arrows button", keywords: ["refresh", "cycle", "repeat", "sync"] },
      { emoji: "⬆️", name: "up arrow", keywords: ["up", "arrow", "north", "direction"] },
      { emoji: "↗️", name: "up-right arrow", keywords: ["up", "right", "arrow", "diagonal"] },
      { emoji: "➡️", name: "right arrow", keywords: ["right", "arrow", "east", "direction"] },
      { emoji: "↘️", name: "down-right arrow", keywords: ["down", "right", "arrow", "diagonal"] },
      { emoji: "⬇️", name: "down arrow", keywords: ["down", "arrow", "south", "direction"] },
      { emoji: "↙️", name: "down-left arrow", keywords: ["down", "left", "arrow", "diagonal"] },
      { emoji: "⬅️", name: "left arrow", keywords: ["left", "arrow", "west", "direction"] },
      { emoji: "↖️", name: "up-left arrow", keywords: ["up", "left", "arrow", "diagonal"] },
      { emoji: "↕️", name: "up-down arrow", keywords: ["up down", "arrow", "vertical"] },
      { emoji: "↔️", name: "left-right arrow", keywords: ["left right", "arrow", "horizontal"] },
      { emoji: "🔼", name: "upwards button", keywords: ["up", "triangle", "button"] },
      { emoji: "🔽", name: "downwards button", keywords: ["down", "triangle", "button"] },
      { emoji: "⏫", name: "fast up button", keywords: ["up", "fast", "double", "arrow"] },
      { emoji: "⏬", name: "fast down button", keywords: ["down", "fast", "double", "arrow"] },
      { emoji: "🔵", name: "blue circle", keywords: ["blue", "circle", "dot", "ball"] },
      { emoji: "🟣", name: "purple circle", keywords: ["purple", "circle", "dot"] },
      { emoji: "🔴", name: "red circle", keywords: ["red", "circle", "dot", "stop"] },
      { emoji: "🟠", name: "orange circle", keywords: ["orange", "circle", "dot"] },
      { emoji: "🟡", name: "yellow circle", keywords: ["yellow", "circle", "dot"] },
      { emoji: "🟢", name: "green circle", keywords: ["green", "circle", "dot", "go"] },
      { emoji: "⚫", name: "black circle", keywords: ["black", "circle", "dot"] },
      { emoji: "⚪", name: "white circle", keywords: ["white", "circle", "dot"] },
      { emoji: "🟤", name: "brown circle", keywords: ["brown", "circle", "dot"] },
      { emoji: "🔶", name: "large orange diamond", keywords: ["diamond", "orange", "large"] },
      { emoji: "🔷", name: "large blue diamond", keywords: ["diamond", "blue", "large"] },
      { emoji: "🔸", name: "small orange diamond", keywords: ["diamond", "orange", "small"] },
      { emoji: "🔹", name: "small blue diamond", keywords: ["diamond", "blue", "small"] },
      { emoji: "🔺", name: "red triangle pointed up", keywords: ["triangle", "red", "up", "warning"] },
      { emoji: "🔻", name: "red triangle pointed down", keywords: ["triangle", "red", "down"] },
      { emoji: "💠", name: "diamond with a dot", keywords: ["diamond", "dot", "blue", "jewel"] },
      { emoji: "🔘", name: "radio button", keywords: ["radio", "button", "circle", "dot"] },
      { emoji: "🔲", name: "black square button", keywords: ["square", "black", "button"] },
      { emoji: "🔳", name: "white square button", keywords: ["square", "white", "button"] },
      { emoji: "⬛", name: "black large square", keywords: ["square", "black", "block"] },
      { emoji: "⬜", name: "white large square", keywords: ["square", "white", "block"] },
      { emoji: "◼️", name: "black medium square", keywords: ["square", "black", "medium"] },
      { emoji: "◻️", name: "white medium square", keywords: ["square", "white", "medium"] },
      { emoji: "🟧", name: "orange square", keywords: ["square", "orange"] },
      { emoji: "🟦", name: "blue square", keywords: ["square", "blue"] },
      { emoji: "🟥", name: "red square", keywords: ["square", "red"] },
      { emoji: "🟩", name: "green square", keywords: ["square", "green"] },
      { emoji: "🟨", name: "yellow square", keywords: ["square", "yellow"] },
      { emoji: "🟪", name: "purple square", keywords: ["square", "purple"] },
      { emoji: "🟫", name: "brown square", keywords: ["square", "brown"] },
      { emoji: "⭐", name: "star", keywords: ["star", "favorite", "rating", "gold", "yellow"] },
      { emoji: "🌟", name: "glowing star", keywords: ["star", "glow", "sparkle", "shine"] },
      { emoji: "💫", name: "dizzy", keywords: ["star", "dizzy", "spin", "sparkle"] },
      { emoji: "✨", name: "sparkles", keywords: ["sparkle", "glitter", "shine", "magic", "star"] },
      { emoji: "🌠", name: "shooting star", keywords: ["shooting star", "wish", "sky", "night"] },
      { emoji: "☀️", name: "sun", keywords: ["sun", "sunny", "hot", "summer", "weather"] },
      { emoji: "🌤️", name: "sun behind small cloud", keywords: ["sun", "cloud", "partly", "weather"] },
      { emoji: "🌈", name: "rainbow", keywords: ["rainbow", "color", "rain", "sky", "pride"] },
      { emoji: "❓", name: "red question mark", keywords: ["question", "what", "ask", "huh", "?"] },
      { emoji: "❔", name: "white question mark", keywords: ["question", "ask", "what", "white", "?"] },
      { emoji: "❗", name: "red exclamation mark", keywords: ["exclamation", "important", "surprise", "!"] },
      { emoji: "❕", name: "white exclamation mark", keywords: ["exclamation", "important", "white", "!"] },
      { emoji: "‼️", name: "double exclamation mark", keywords: ["exclamation", "important", "!!"] },
      { emoji: "⁉️", name: "exclamation question mark", keywords: ["?!", "surprise", "confused"] },
      { emoji: "💯", name: "hundred points", keywords: ["100", "perfect", "score", "full", "tops"] },
      { emoji: "🔅", name: "dim button", keywords: ["dim", "low", "brightness", "button"] },
      { emoji: "🔆", name: "bright button", keywords: ["bright", "high", "brightness", "button"] },
      { emoji: "💥", name: "collision", keywords: ["boom", "explosion", "bang", "impact"] },
      { emoji: "💢", name: "anger symbol", keywords: ["anger", "mad", "comic", "symbol"] },
      { emoji: "💦", name: "sweat droplets", keywords: ["sweat", "water", "drops", "splash"] },
      { emoji: "💨", name: "dashing away", keywords: ["run", "dash", "wind", "blow", "fast"] },
      { emoji: "🕳️", name: "hole", keywords: ["hole", "empty", "tunnel", "void"] },
      { emoji: "💬", name: "speech balloon", keywords: ["chat", "comment", "talk", "speech", "message"] },
      { emoji: "💭", name: "thought balloon", keywords: ["thought", "thinking", "mind", "ponder"] },
      { emoji: "💤", name: "zzz", keywords: ["sleep", "zzz", "tired", "snore", "rest"] },
    ],
  },
  {
    id: "flags",
    label: "Flags",
    icon: "🏳️",
    emojis: [
      { emoji: "🏳️", name: "white flag", keywords: ["white", "flag", "surrender", "peace"] },
      { emoji: "🏴", name: "black flag", keywords: ["black", "flag", "pirate", "dark"] },
      { emoji: "🚩", name: "triangular flag", keywords: ["flag", "red", "pole", "mark", "checkpoint"] },
      { emoji: "🏴‍☠️", name: "pirate flag", keywords: ["pirate", "skull", "flag", "jolly roger"] },
      { emoji: "🏳️‍🌈", name: "rainbow flag", keywords: ["rainbow", "flag", "pride", "lgbtq", "gay"] },
      { emoji: "🏳️‍⚧️", name: "transgender flag", keywords: ["transgender", "trans", "flag", "lgbtq"] },
      { emoji: "🇺🇸", name: "flag united states", keywords: ["usa", "america", "flag", "united states"] },
      { emoji: "🇬🇧", name: "flag united kingdom", keywords: ["uk", "britain", "england", "flag", "union jack"] },
      { emoji: "🇨🇦", name: "flag canada", keywords: ["canada", "flag", "maple leaf"] },
      { emoji: "🇦🇺", name: "flag australia", keywords: ["australia", "flag", "down under"] },
      { emoji: "🇩🇪", name: "flag germany", keywords: ["germany", "flag", "deutsch"] },
      { emoji: "🇫🇷", name: "flag france", keywords: ["france", "flag", "french"] },
      { emoji: "🇯🇵", name: "flag japan", keywords: ["japan", "flag", "japanese", "nihon"] },
      { emoji: "🇨🇳", name: "flag china", keywords: ["china", "flag", "chinese"] },
      { emoji: "🇮🇳", name: "flag india", keywords: ["india", "flag", "indian"] },
      { emoji: "🇧🇷", name: "flag brazil", keywords: ["brazil", "flag", "brasil"] },
      { emoji: "🇲🇽", name: "flag mexico", keywords: ["mexico", "flag", "mexican"] },
      { emoji: "🇮🇹", name: "flag italy", keywords: ["italy", "flag", "italian"] },
      { emoji: "🇷🇺", name: "flag russia", keywords: ["russia", "flag", "russian"] },
      { emoji: "🇪🇸", name: "flag spain", keywords: ["spain", "flag", "spanish"] },
      { emoji: "🇰🇷", name: "flag south korea", keywords: ["korea", "flag", "korean"] },
      { emoji: "🇿🇦", name: "flag south africa", keywords: ["south africa", "flag"] },
      { emoji: "🇳🇬", name: "flag nigeria", keywords: ["nigeria", "flag", "nigerian"] },
      { emoji: "🇦🇷", name: "flag argentina", keywords: ["argentina", "flag", "argentinian"] },
      { emoji: "🇸🇦", name: "flag saudi arabia", keywords: ["saudi", "arabia", "flag"] },
      { emoji: "🇦🇪", name: "flag united arab emirates", keywords: ["uae", "dubai", "flag", "arab"] },
      { emoji: "🇵🇰", name: "flag pakistan", keywords: ["pakistan", "flag", "pakistani"] },
      { emoji: "🇧🇩", name: "flag bangladesh", keywords: ["bangladesh", "flag"] },
      { emoji: "🇮🇩", name: "flag indonesia", keywords: ["indonesia", "flag", "indonesian"] },
      { emoji: "🇳🇱", name: "flag netherlands", keywords: ["netherlands", "holland", "flag", "dutch"] },
      { emoji: "🇧🇪", name: "flag belgium", keywords: ["belgium", "flag", "belgian"] },
      { emoji: "🇨🇭", name: "flag switzerland", keywords: ["switzerland", "swiss", "flag"] },
      { emoji: "🇸🇪", name: "flag sweden", keywords: ["sweden", "flag", "swedish"] },
      { emoji: "🇳🇴", name: "flag norway", keywords: ["norway", "flag", "norwegian"] },
      { emoji: "🇵🇱", name: "flag poland", keywords: ["poland", "flag", "polish"] },
      { emoji: "🇵🇹", name: "flag portugal", keywords: ["portugal", "flag", "portuguese"] },
      { emoji: "🇬🇷", name: "flag greece", keywords: ["greece", "flag", "greek"] },
      { emoji: "🇹🇷", name: "flag turkey", keywords: ["turkey", "flag", "turkish"] },
      { emoji: "🇵🇭", name: "flag philippines", keywords: ["philippines", "flag", "filipino"] },
      { emoji: "🇻🇳", name: "flag vietnam", keywords: ["vietnam", "flag", "vietnamese"] },
      { emoji: "🇹🇭", name: "flag thailand", keywords: ["thailand", "flag", "thai"] },
      { emoji: "🇺🇦", name: "flag ukraine", keywords: ["ukraine", "flag", "ukrainian"] },
      { emoji: "🇮🇷", name: "flag iran", keywords: ["iran", "flag", "iranian"] },
      { emoji: "🇮🇱", name: "flag israel", keywords: ["israel", "flag", "israeli"] },
      { emoji: "🇪🇬", name: "flag egypt", keywords: ["egypt", "flag", "egyptian"] },
      { emoji: "🇰🇪", name: "flag kenya", keywords: ["kenya", "flag", "kenyan"] },
      { emoji: "🇬🇭", name: "flag ghana", keywords: ["ghana", "flag", "ghanaian"] },
      { emoji: "🇨🇴", name: "flag colombia", keywords: ["colombia", "flag", "colombian"] },
      { emoji: "🇨🇱", name: "flag chile", keywords: ["chile", "flag", "chilean"] },
      { emoji: "🇵🇪", name: "flag peru", keywords: ["peru", "flag", "peruvian"] },
      { emoji: "🇳🇿", name: "flag new zealand", keywords: ["new zealand", "flag", "kiwi"] },
    ],
  },
];

/** Flat list of all emojis for simple keyword search */
export const ALL_EMOJIS: EmojiItem[] = EMOJI_CATEGORIES.flatMap((c) => c.emojis);
